package com.nqvinh.rentofficebackend.domain.common.constant;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldDefaults;

@RequiredArgsConstructor
@Getter
@FieldDefaults(makeFinal = true, level = lombok.AccessLevel.PRIVATE)
public enum MailType {
    RESET_PASSWORD("RESET_PASSWORD"),
    CONFIRMED_BUILDING("CONFIRMED_BUILDING"),
    CANCELLED_BUILDING("CANCELLED_BUILDING"),
    PENDING_BUILDING("PENDING_BUILDING"),
    CONFIRM_APPOINTMENT("CONFIRM_APPOINTMENT"),
    INCOMPLETE_CONSIGNMENT("INCOMPLETE_CONSIGNMENT"),
    CREATE_CUSTOMER_POTENTIAL("CREATE_CUSTOMER_POTENTIAL"),
    NOTIFICATION_CREATE_BUILDING("NOTIFICATION_CREATE_BUILDING"),
    NOTIFICATION_UPDATE_INFO_BUILDING("NOTIFICATION_UPDATE_INFO_BUILDING"),
    NOTIFICATION_ASSIGN_CUSTOMER("NOTIFICATION_ASSIGN_CUSTOMER"),
    NOTIFICATION_ASSIGN_BUILDING("NOTIFICATION_ASSIGN_BUILDING"),
    NOTIFICATION_CREATE_CUSTOMER_POTENTIAL("NOTIFICATION_CREATE_CUSTOMER_POTENTIAL");
    String type;
}
